### ISSUE TITLE
AlignmentHeader does not support item assignment

### ISSUE THREAD

**Issue by Char-Al** [bialimed/AnaCore-utils#1]
Hi,

It seems that pysam v0.15.3 is not compatible.
It looks very similar of this issue  : https://github.com/namphuon/ViFi/issues/9

See log :
> \> ampliVariantCalling.py \\ 
    -g ${GENOME_REF} \\
    -pi ${DESIGN_PATH}/withPrimers.bed  \\
    -po ${DESIGN_PATH}/woutPrimers.bed  \\
    -pg ${DESIGN_PATH}/nonOverlappingGroups.tsv \\
    -l "${SAMPLE}" -a ${OUTPUT_TMP}/${SAMPLE}.RG.bam \\
    -ov ${OUTPUT_TMP}/${SAMPLE}.vcf \\
    -ol ${OUTPUT_TMP}/${SAMPLE}.log
_Traceback (most recent call last):
  File "/bin/anaconda3/envs/TEST_anacore/bin/splitBAMByRG.py", line 72, in <module>
    new_header["RG"] = [curr_RG for curr_RG in FH_in.header["RG"] if group_by_tag[curr_RG[args.RG_tag]] == group]
  **File "pysam/libcalignmentfile.pyx", line 544, in pysam.libcalignmentfile.AlignmentHeader.__setitem__
TypeError: AlignmentHeader does not support item assignment (use header.to_dict()**
Traceback (most recent call last):
  File "/bin/anaconda3/envs/TEST_anacore/bin/ampliVariantCalling.py", line 557, in <module>
    SplitBAMByRG(args.input_non_overlapping_design, args.input_aln, out_bam_pattern).submit(args.output_log)
  File "/bin/anaconda3/envs/TEST_anacore/bin/ampliVariantCalling.py", line 112, in submit
    subprocess.check_output(self.get_cmd(), shell=True)
  File "/bin/anaconda3/envs/TEST_anacore/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/bin/anaconda3/envs/TEST_anacore/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'splitBAMByRG.py  --input-design ${DESIGN_PATH}/nonOverlappingGroups.tsv --input-aln${OUTPUT_TMP}/${SAMPLE}.RG.bam --output-pattern ${OUTPUT_TMP}/1580394752.121624_10888_{GP}.bam' returned non-zero exit status 1._

**Comment by fescudie** [comment]
Hi,

Thanks for your report. This is an oversight of commit e5b7e2a17d4b4b9fe14e91f18c0d10e57feb5644.
I fixed this bug in the dev branch (commit: 025b1357abe96cafdc347ad488b14bbb03430c41). This fix will be merged into the master branch at the end of next week.

**Comment by Char-Al** [comment]
Thank you !
